### ISSUE TITLE
Expected Waiting Time For Adding Tseries

### ISSUE THREAD

**Issue by MaximilianHoffmann** [losonczylab/roibuddy#15]
Hello again. 
If I open a timeseries object of about 5 frames (1 y plane) , everything  goes verz smooth. 
However when I try this with a dataset, that is comprised of 1000 frames the GUI immediately freezes. I still get one user waring about a polygon that did not carry a set coordinate in the spyder console, then at a timescale of 30 min nothing seemed to happen. Is this expected?

Many Thanks

**Comment by MaximilianHoffmann** [comment]
300 frames -> freeze of 1 s  , 500 frames -> freeze of 5 s , 700 frames 18 s , 1000 frames -> 30s on i7-4790 3.6 GHz , 32GB memory.
Thats ok,I am very sorry , I dont know, why it was not woking before.

**Comment by jzaremba** [comment]
No problem, glad it's working now.

ROIBuddy only loads the time average of the time series, so in general load time should be independent of the length of the time series (load time will scale with the number of ROIs it needs to draw).

That being said, the first time a SIMA dataset needs the time average it is calculated on the fly, but then saved for future calls. So, the long initial load was most likely the time to calculate the time average (which requires reading the entire time series, and can be slow), but subsequently it should be much faster.

In our data workflow, we export time averages as TIFFs immediately after motion correcting and creating our SIMA datasets, so that in the future accessing the time average of the datasets is nearly instantaneous.

**Comment by MaximilianHoffmann** [comment]
Indeed , this was very noisy 2p data and in found 9000 rois or so, which was an overload. After size filtering it then worked. However it should also be able to deal with 9000 polygons , shouldn't it?

Many Thanks
Max

**Comment by jzaremba** [comment]
We've never actually tested it with beyond ~1000 ROIs. I would expect it to be somewhat slow, but it should work.

We're somewhat limited by the plotting library that we use (guiqwt), so I'm not sure how much we'd be improve that.

**Comment by dz-bendog** [comment]
Not sure it's preferable to comment on a closed issue, but I'll try since I'm having similar problem.
First of all thanks for the great tool! It'll be really nice to see it working faster.
So I'm trying to load a dataset with moderate number (I think) of ROIs, but the speed seems abnormal.
Currently the only time it worked is when I have 79 ROIs, and that took around 20min.
Then when I try to open the same dataset with 279 ROIs it just freeze and I never have enough patience to wait for 30+ mins to see if anything would happen after that.
Just want to make sure if this is expected and I just have to be patient? Besides, would it be possible to add a progress bar for drawing ROIs instead of freezing?
I'm running it on i7-6700K @ 4GHz with 32g RAM, and it seems roibuddy never consume noticeable amount of resource, it just freeze.
Thank you in advance for the help!
